---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:7
    command: /usr/lib/systemd/systemd
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian10
    image: geerlingguy/docker-debian10-ansible:latest
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
  pre_tasks:
    - name: install gnupg
      ansible.builtin.package:
        name: gnupg
        state: present
verifier:
  name: ansible
  options:
    inventory: inventory.yml
    ansible_cfg: ansible.cfg
scenario:
  test_sequence:
    - create
    - prepare
    - converge

