---
- name: Install Terraform
  hosts: all
  become: yes
  remote_user: root
  vars:
    terraform_version: "1.1.0" # change this to the version you want to install

  tasks:
    - name: sudo install
      command: yum install sudo -y 
      when: ansible_os_family == "RedHat"    

    - name: update cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      when: ansible_os_family == "Debian" 

    - name: Install required packages
      package:
        name:
          - unzip
          - wget
        state: present

    - name: Download and install Terraform
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
        mode: '0644'
      when: ansible_os_family == "Debian"

    - name: Download and install Terraform
      get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
        mode: '0644'
      when: ansible_os_family == "RedHat"

    - name: Extract Terraform binary
      unarchive:
        src: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "/usr/local/bin"
        copy: no
        mode: '0755'
        creates: "/usr/local/bin/terraform"
