---
 - name: Create an EC2 instance
   command: aws ec2 run-instances
            --image-id ami-0c94855ba95c71c99
            --count 1
            --instance-type t2.micro
            --key-name my-key-pair
            --security-group-ids sg-1234567890abcdef0
