---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    version: 1.4.0
  tasks:
    - name: check terraform version
      command: "terraform version"
      register: terraform_version

    - name: check terraform install correctly 
      assert:
        that:
          - 'version in terraform_version.stdout'
        fail_msg: "terraform version incorrect"
        success_msg: "terraform installed correctly with version {{ version }}"