name: Molecule

on:
  push:
    branches:
      - main
      - fix/RAD-614
  pull_request_target:
    types:
      - opened
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['centos7', 'debian10']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Install Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y python3-pip
      #     pip3 install molecule[docker] ansible
      #     sudo systemctl start docker
      #     ansible-galaxy collection install community.docker
      #     ansible-galaxy collection install ansible.posix

      - name: Molecule Test
        run: |
          cd ${{ github.workspace }}/${{ github.event.pull_request.head.repo.name }}
          ls -lrth
          # molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

